Kg   shodenna
Cu7ious/Promin-App pull request #42
Opened 2022-07-12 04:24 UTC by Keeppie

Added text to Shodenna page with 9 buttons that lead to 9 other pages with text in them

2022-07-12 06:02 UTC, garys-primary requested changes
Please see comments. Otherwise - great job

2022-07-12 06:02 UTC, garys-primary commented on Routes/MainStack.js
> +  import YaMau from "../screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/YaMau";
please fix formatting (remove extra spaces) for all above lines

2022-07-12 06:02 UTC, garys-primary commented on Routes/MainStack.js
> +  import YaMau from "../screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/YaMau";
Also make paths absolute (/screens instead of ../screens)

2022-07-12 06:02 UTC, garys-primary commented on Routes/MainStack.js
> +        <Stack.Screen name="YaMau" component={YaMau} />
Formatting

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/Shodenna.js
> +  const navigateAway = () => {// eslint-disable-next-line no-console console.log("navigation");
please remove this function

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/ChernoBilaCadr.js
> + };
also remove function

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/CheroBilaFoto.js
> +CheroBilaFoto
please remove this line

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/Kvitka.js
> +Kvitka
please remove this

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/Shvidkii.js
> +Shvidkii
please remove this line

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/Shvidkii.js
> +----------SubBullet (needs space):
please comment this out with //

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/Shvidkii.js
> +-----------End of SubBullet
please comment this out

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/Spokiine.js
> +Spokiine
please remove this line

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/Tehnika.js
> +Tehnika
please remove this line

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/VnutrishniiSad.js
> +VnutrishniiSad
please remove this line

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/VnutrishniiSeif.js
> +VnutrishniiSeif
please remove

2022-07-12 06:02 UTC, garys-primary commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/YaMau.js
> +YaMau
please remove

2022-07-12 06:32 UTC, Keeppie commented on screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/ChernoBilaCadr.js
> + };
Everything? line 14 to 17th?

2022-07-12 06:33 UTC, Keeppie commented on Routes/MainStack.js
> +  import YaMau from "../screens/psychologichnaDopomoga/dlyaSebe/dlyaSebeScreens/ShodennaFile/YaMau";
Forgot about it =)

2022-07-13 02:18 UTC, garys-primary approved these changes
Good job!

2022-07-13 02:19 UTC, merged